---
title: "group_IP"
author: "Liv Depies, Maddy Doak, Michael Kuranty"
date: "12/1/2019"
output: pdf_document
---

```{r setup, include=FALSE}
library(readxl)
library(dplyr)
library(ggplot2)
library(BiocGenerics)

# Importing data and renaming columns
# Then adding columns for subject and trial numbers
file_extension <- "/media/maddy/Seagate Portable Drive/git/Bio_381/group_IP/excel_data/"
data <- vector("list",5)
for (num in 1:5) {
  data[[num]] <- as_tibble(read_excel(paste(file_extension,"Data_",num,".xlsx",sep="")))
  colnames(data[[num]]) <- c("time","Ch1_mean", "Ch1_amp", "Ch1_time_max",
                             "Ch1_time_min", "Ch2_mean", "Ch2_amp", "Ch2_time_max",
                             "Ch2_time_min","Ch3_mean", "Ch3_amp", "Ch3_time_max",
                             "Ch3_time_min", "Ch4_mean", "Ch4_amp", "Ch4_time_max",
                             "Ch4_time_min")
  data[[num]] <- data[[num]] %>% mutate(subject = c(num), phrase = c(NA), spoken = c("Yes"))
  data[[num]] <- data[[num]][,c(1,18,19,20,2:17)]
}

# Removing header lines and non-trials
for (i in 2:5) {
  data[[i]] <- data[[i]][-c(1,2),]
}
data[[1]] <- data[[1]][-c(1),]
data[[1]] <- data[[1]][-c(280:282,284:286),]
data[[3]] <- data[[3]][-c(142),]
data[[3]] <- data[[3]][-c(53:55,57:59),]
data[[4]] <- data[[4]][-c(1,2),]
data[[4]] <- data[[4]][-c(158),]
data[[5]] <- data[[5]][-c(56:58,60:62),]

# Adding numbering for phrases/whether they're spoken or silent
for (num in 1:5) {
  new_set <- which(grepl(paste("^","0","$",sep=""),data[[num]]$time))
  new_set <- append(new_set, length(data[[num]][[1]]))
  for (i in 1:20) {
    if (i > 10) {
      data[[num]][new_set[[i]]:new_set[[i+1]],"phrase"] <- i-10
      data[[num]][new_set[[i]]:new_set[[i+1]],"spoken"] <- "No"
    } else {
      data[[num]][new_set[[i]]:new_set[[i+1]],"phrase"] <- i
    }
  }
}

# Combining all data into one dataframe
all_data <- do.call(rbind,data)
View(all_data)
```

```{r}
# Graphs by channel

subj_labels <- c("Subject 1", "Subject 2", "Subject 3", "Subject 4", "Subject 5")
names(subj_labels) <- c("1","2","3","4","5")

# Channel 1
p1_1 <- all_data %>% 
  group_by(subject,phrase,spoken) %>%
  filter(!is.na(Ch1_amp)) %>%
  summarize(phrase_mean = mean(as.numeric(Ch1_amp),na.rm=TRUE))

res.aov.ch1 <- aov(phrase_mean ~ spoken, data=p1_1)
summary(res.aov.ch1)

res.aov2.ch1 <- aov(phrase_mean ~ spoken * phrase, data=p1_1)
summary(res.aov2.ch1)

p1_1_plot <- p1_1 %>% ggplot(aes(x=factor(phrase),y=phrase_mean,fill=spoken)) +
    geom_bar(position="dodge",stat="identity") +
    facet_wrap(~ subject, ncol = 2, labeller = labeller(subject = subj_labels)) +
    labs(x="Phrase Number",y="Mean Amplitude for Phrase (mV)",
         title="Ch1: Mean Amplitude by Subject/Phrase/Vocalization Condition")
png(file='ch1_mean_amp_by_conditions.png')
p1_1_plot
dev.off()
p1_2 <- all_data %>% 
  group_by(subject,phrase,spoken) %>%
  filter(!is.na(Ch1_amp)) %>%
  summarize(phrase_mean = mean(as.numeric(Ch1_amp),na.rm=TRUE)) %>%
  mutate(phrase_diff = phrase_mean - lag(phrase_mean)) %>%
  ggplot(aes(x=factor(phrase),y=phrase_diff)) +
    geom_bar(stat="identity") +
    facet_wrap(~ subject, ncol = 2, labeller = labeller(subject = subj_labels)) +
    labs(x="Phrase Number",y="Difference in Mean Amplitude (Spoken-Silent)",
         title="Ch1: Difference in Mean Amplitude Between Conditions by Phrase")
png(file='ch1_diff_mean_amp.png')
p1_2
dev.off()

# Channel 2
p2_1 <- all_data %>% 
  filter(subject != 4) %>%
  group_by(subject,phrase,spoken) %>%
  filter(!is.na(Ch2_amp)) %>%
  summarize(phrase_mean = mean(as.numeric(Ch2_amp),na.rm=TRUE))

res.aov.ch2 <- aov(phrase_mean ~ spoken, data=p2_1)
summary(res.aov.ch2)

res.aov2.ch2 <- aov(phrase_mean ~ spoken * phrase, data=p2_1)
summary(res.aov2.ch2)

p2_1_plot <- p2_1 %>% ggplot(aes(x=factor(phrase),y=phrase_mean,fill=spoken)) +
    geom_bar(position="dodge",stat="identity") +
    facet_wrap(~ subject, ncol = 2, labeller = labeller(subject = subj_labels)) +
    labs(x="Phrase Number",y="Mean Amplitude for Phrase (mV)",
         title="Ch2: Mean Amplitude by Subject/Phrase/Vocalization Condition")
png(file='ch2_mean_amp_by_conditions.png')
p2_1_plot
dev.off()
p2_2 <- all_data %>% 
  group_by(subject,phrase,spoken) %>%
  filter(!is.na(Ch2_amp)) %>%
  summarize(phrase_mean = mean(as.numeric(Ch2_amp),na.rm=TRUE)) %>%
  mutate(phrase_diff = phrase_mean - lag(phrase_mean)) %>%
  ggplot(aes(x=factor(phrase),y=phrase_diff)) +
    geom_bar(stat="identity") +
    facet_wrap(~ subject, ncol = 2, labeller = labeller(subject = subj_labels)) +
    labs(x="Phrase Number",y="Difference in Mean Amplitude (Spoken-Silent)",
         title="Ch2: Difference in Mean Amplitude Between Conditions by Phrase")
png(file='ch2_diff_mean_amp.png')
p2_2
dev.off()

# Channel 3
p3 <- all_data %>% 
  group_by(subject,phrase,spoken) %>%
  filter(!is.na(Ch3_amp)) %>%
  summarize(phrase_mean = mean(as.numeric(Ch3_amp),na.rm=TRUE))  %>%
  mutate(phrase_diff = phrase_mean - lag(phrase_mean))

res.aov.ch3 <- aov(phrase_mean ~ spoken, data=p3)
summary(res.aov.ch3)

res.aov2.ch3 <- aov(phrase_mean ~ spoken * phrase, data=p3)
summary(res.aov2.ch3)

p3_1 <- p3 %>% ggplot(aes(x=factor(phrase),y=phrase_mean,fill=spoken)) +
    geom_bar(position="dodge",stat="identity") +
    facet_wrap(~ subject, ncol = 2, labeller = labeller(subject = subj_labels)) +
    labs(x="Phrase Number",y="Mean Amplitude for Phrase (mV)",
         title="Ch3: Mean Amplitude by Subject/Phrase/Vocalization Condition")
png(file='ch3_mean_amp_by_conditions.png')
p3_1
dev.off()
p3_2 <- p3 %>% ggplot(aes(x=factor(phrase),y=phrase_diff)) +
    geom_bar(stat="identity") +
    facet_wrap(~ subject, ncol = 2, labeller = labeller(subject = subj_labels)) +
    labs(x="Phrase Number",y="Difference in Mean Amplitude (Spoken-Silent)",
         title="Ch3: Difference in Mean Amplitude Between Conditions by Phrase")
png(file='ch3_diff_mean_amp.png')
p3_2
dev.off()

# Channel 3, Subject 3
p3_3 <- all_data %>% 
  filter(subject==3) %>%
  group_by(phrase,spoken) %>%
  filter(!is.na(Ch3_amp)) %>%
  summarize(phrase_mean = mean(as.numeric(Ch3_amp),na.rm=TRUE))  %>%
  mutate(phrase_diff = phrase_mean - lag(phrase_mean))
p3_3_1 <- p3_3 %>% ggplot(aes(x=factor(phrase),y=phrase_mean,fill=spoken)) +
    geom_bar(position="dodge",stat="identity") +
    labs(x="Phrase Number",y="Mean Amplitude for Phrase (mV)",
         title="Ch3/Sbj3: Mean Amplitude by Phrase/Vocalization Condition")
png(file='ch3_sbj3_mean_amp_by_conditions.png')
p3_3_1
dev.off()
p3_3_2 <- p3_3 %>% ggplot(aes(x=factor(phrase),y=phrase_diff)) +
    geom_bar(stat="identity") +
    labs(x="Phrase Number",y="Difference in Mean Amplitude (Spoken-Silent)",
         title="Ch3/Sbj3: Difference in Mean Amplitude Between Conditions by Phrase")
png(file='ch3_sbj3_diff_mean_amp.png')
p3_3_2
dev.off()

# Channel 4
p4_1 <- all_data %>% 
  group_by(subject,phrase,spoken) %>%
  filter(!is.na(Ch4_amp)) %>%
  summarize(phrase_mean = mean(as.numeric(Ch4_amp),na.rm=TRUE))

# ANOVA channel 4:
res.aov.ch4 <- aov(phrase_mean ~ spoken, data=p4_1)
summary(res.aov.ch4)

res.aov2.ch4 <- aov(phrase_mean ~ spoken * phrase, data=p4_1)
summary(res.aov2.ch4)

p4_1_plot <- p4_1 %>% ggplot(aes(x=factor(phrase),y=phrase_mean,fill=spoken)) +
    geom_bar(position="dodge",stat="identity") +
    facet_wrap(~ subject, ncol = 2, labeller = labeller(subject = subj_labels)) +
    labs(x="Phrase Number",y="Mean Amplitude for Phrase (mV)",
         title="Ch4: Mean Amplitude by Subject/Phrase/Vocalization Condition")
png(file='ch4_mean_amp_by_conditions.png')
p4_1_plot
dev.off()
p4_2 <- all_data %>% 
  group_by(subject,phrase,spoken) %>%
  filter(!is.na(Ch4_amp)) %>%
  summarize(phrase_mean = mean(as.numeric(Ch4_amp),na.rm=TRUE)) %>%
  mutate(phrase_diff = phrase_mean - lag(phrase_mean)) %>%
  ggplot(aes(x=factor(phrase),y=phrase_diff)) +
    geom_bar(stat="identity") +
    facet_wrap(~ subject, ncol = 2, labeller = labeller(subject = subj_labels)) +
    labs(x="Phrase Number",y="Difference in Mean Amplitude (Spoken-Silent)",
         title="Ch4: Difference in Mean Amplitude Between Conditions by Phrase")
png(file='ch4_diff_mean_amp.png')
p4_2
dev.off()
```

```{r}
# Graphs by subject
subj_labels <- c("Subject 1", "Subject 2", "Subject 3", "Subject 4", "Subject 5")
names(subj_labels) <- c("1","2","3","4","5")

library(reshape2)
# Subject 1
p_sub1 <- all_data %>% 
  filter(subject == 1) %>%
  group_by(phrase,spoken) %>%
  summarize(Ch1_mean = mean(as.numeric(Ch1_amp),na.rm=TRUE),
            Ch2_mean = mean(as.numeric(Ch2_amp),na.rm=TRUE),
            Ch3_mean = mean(as.numeric(Ch3_amp),na.rm=TRUE),
            Ch4_mean = mean(as.numeric(Ch4_amp),na.rm=TRUE)) %>%
  mutate(Ch1_diff = Ch1_mean - lag(Ch1_mean),
         Ch2_diff = Ch2_mean - lag(Ch2_mean),
         Ch3_diff = Ch3_mean - lag(Ch3_mean),
         Ch4_diff = Ch4_mean - lag(Ch4_mean))
p_sub1_m <- melt(p_sub1[,c('phrase','Ch1_diff','Ch2_diff','Ch3_diff','Ch4_diff')],id.vars=1)
png(file='sbj1_diff_mean_amp.png')
ggplot(p_sub1_m, aes(x=factor(phrase), y=value)) +
    geom_bar(aes(fill=variable),stat="identity",position="dodge") +
    labs(x="Phrase Number",y="Difference in Mean Amplitude (Spoken-Silent)",
         title="Subject 1: Diff in Mean Amplitude Between Conditions by Phrase",
         fill="Muscle")
dev.off()

# Subject 2
p_sub2 <- all_data %>% 
  filter(subject == 2) %>%
  group_by(phrase,spoken) %>%
  summarize(Ch1_mean = mean(as.numeric(Ch1_amp),na.rm=TRUE),
            Ch2_mean = mean(as.numeric(Ch2_amp),na.rm=TRUE),
            Ch3_mean = mean(as.numeric(Ch3_amp),na.rm=TRUE),
            Ch4_mean = mean(as.numeric(Ch4_amp),na.rm=TRUE)) %>%
  mutate(Ch1_diff = Ch1_mean - lag(Ch1_mean),
         Ch2_diff = Ch2_mean - lag(Ch2_mean),
         Ch3_diff = Ch3_mean - lag(Ch3_mean),
         Ch4_diff = Ch4_mean - lag(Ch4_mean))
p_sub2_m <- melt(p_sub2[,c('phrase','Ch1_diff','Ch2_diff','Ch3_diff','Ch4_diff')],id.vars=1)
png(file='sbj2_diff_mean_amp.png')
ggplot(p_sub2_m, aes(x=factor(phrase), y=value)) +
    geom_bar(aes(fill=variable),stat="identity",position="dodge") +
    labs(x="Phrase Number",y="Difference in Mean Amplitude (Spoken-Silent)",
         title="Subject 2: Diff in Mean Amplitude Between Conditions by Phrase",
         fill="Muscle")
dev.off()

# Subject 3
p_sub3 <- all_data %>% 
  filter(subject == 3) %>%
  group_by(phrase,spoken) %>%
  summarize(Ch1_mean = mean(as.numeric(Ch1_amp),na.rm=TRUE),
            Ch2_mean = mean(as.numeric(Ch2_amp),na.rm=TRUE),
            Ch3_mean = mean(as.numeric(Ch3_amp),na.rm=TRUE),
            Ch4_mean = mean(as.numeric(Ch4_amp),na.rm=TRUE)) %>%
  mutate(Ch1_diff = Ch1_mean - lag(Ch1_mean),
         Ch2_diff = Ch2_mean - lag(Ch2_mean),
         Ch3_diff = Ch3_mean - lag(Ch3_mean),
         Ch4_diff = Ch4_mean - lag(Ch4_mean))
p_sub3_m <- melt(p_sub3[,c('phrase','Ch1_diff','Ch2_diff','Ch3_diff','Ch4_diff')],id.vars=1)
png(file='sbj3_diff_mean_amp.png')
ggplot(p_sub3_m, aes(x=factor(phrase), y=value)) +
    geom_bar(aes(fill=variable),stat="identity",position="dodge") +
    labs(x="Phrase Number",y="Difference in Mean Amplitude (Spoken-Silent)",
         title="Subject 3: Diff in Mean Amplitude Between Conditions by Phrase",
         fill="Muscle")
dev.off()

# Subject 4
p_sub4 <- all_data %>% 
  filter(subject == 4) %>%
  group_by(phrase,spoken) %>%
  summarize(Ch1_mean = mean(as.numeric(Ch1_amp),na.rm=TRUE),
            Ch2_mean = mean(as.numeric(Ch2_amp),na.rm=TRUE),
            Ch3_mean = mean(as.numeric(Ch3_amp),na.rm=TRUE),
            Ch4_mean = mean(as.numeric(Ch4_amp),na.rm=TRUE)) %>%
  mutate(Ch1_diff = Ch1_mean - lag(Ch1_mean),
         Ch2_diff = Ch2_mean - lag(Ch2_mean),
         Ch3_diff = Ch3_mean - lag(Ch3_mean),
         Ch4_diff = Ch4_mean - lag(Ch4_mean))
p_sub4_m <- melt(p_sub4[,c('phrase','Ch1_diff','Ch2_diff','Ch3_diff','Ch4_diff')],id.vars=1)
png(file='sbj4_diff_mean_amp.png')
ggplot(p_sub4_m, aes(x=factor(phrase), y=value)) +
    geom_bar(aes(fill=variable),stat="identity",position="dodge") +
    labs(x="Phrase Number",y="Difference in Mean Amplitude (Spoken-Silent)",
         title="Subject 4: Diff in Mean Amplitude Between Conditions by Phrase",
         fill="Muscle")
dev.off()

# Subject 5
p_sub5 <- all_data %>% 
  filter(subject == 5) %>%
  group_by(phrase,spoken) %>%
  summarize(Ch1_mean = mean(as.numeric(Ch1_amp),na.rm=TRUE),
            Ch2_mean = mean(as.numeric(Ch2_amp),na.rm=TRUE),
            Ch3_mean = mean(as.numeric(Ch3_amp),na.rm=TRUE),
            Ch4_mean = mean(as.numeric(Ch4_amp),na.rm=TRUE)) %>%
  mutate(Ch1_diff = Ch1_mean - lag(Ch1_mean),
         Ch2_diff = Ch2_mean - lag(Ch2_mean),
         Ch3_diff = Ch3_mean - lag(Ch3_mean),
         Ch4_diff = Ch4_mean - lag(Ch4_mean))
p_sub5_m <- melt(p_sub5[,c('phrase','Ch1_diff','Ch2_diff','Ch3_diff','Ch4_diff')],id.vars=1)
png(file='sbj5_diff_mean_amp.png')
ggplot(p_sub5_m, aes(x=factor(phrase), y=value)) +
    geom_bar(aes(fill=variable),stat="identity",position="dodge") +
    labs(x="Phrase Number",y="Difference in Mean Amplitude (Spoken-Silent)",
         title="Subject 1: Diff in Mean Amplitude Between Conditions by Phrase",
         fill="Muscle")
dev.off()

# Phrase 1
p_phrs1 <- all_data %>% 
  filter(phrase==1) %>%
  group_by(subject,spoken) %>%
  mutate(M1 = mean(as.numeric(Ch1_amp),na.rm=TRUE),
          M2 = mean(as.numeric(Ch2_amp),na.rm=TRUE),
          M3 = mean(as.numeric(Ch3_amp),na.rm=TRUE),
          M4 = mean(as.numeric(Ch4_amp),na.rm=TRUE))
p_phrs1_m <- melt(p_phrs1[,c('subject','spoken','M1','M2','M3','M4')],id.vars=c(1,2))
png(file='phrs1_mean_amp.png')
ggplot(p_phrs1_m, aes(x=factor(variable), y=value)) +
    geom_bar(aes(fill=spoken),stat="identity",position="dodge") +
    facet_wrap(~subject, ncol=2, labeller = labeller(subject = subj_labels)) +
    labs(x="Muscle",y="Mean Amplitude (mV)",
         title="Phrase 1: Mean Amplitude Between Conditions by Subject",
         fill="Vocalized")
dev.off()
```

```{r}
# Peak data
# Channel 1, peaks above 10uV
peak_ch1 <- as_tibble(read.csv2("/media/maddy/Seagate Portable Drive/git/Bio_381/group_IP/peaks_reformat.csv", header=TRUE, sep=","))
peak_ch1$Time_sec <- as.double(as.character(peak_ch1$Time_sec))
peak_ch1$voltage_microv <- as.double(as.character(peak_ch1$voltage_microv))

norm_factor <- peak_ch1 %>% 
  group_by(phrase,vocalization) %>%
  summarize(start_time = min(Time_sec)) %>%
  mutate(time_diff = start_time - lag(start_time)) %>%
  filter(vocalization == "spoken")
View(norm_factor)

normalized <- peak_ch1 %>%
  filter(vocalization == "spoken") %>%
  group_by(phrase) %>%
  mutate(new_time = Time_sec - norm_factor$time_diff[phrase])
normalized <- as_tibble(normalized)
View(normalized)

just_silent <- peak_ch1 %>% filter(vocalization == "silent") %>% mutate(new_time = Time_sec)
just_silent <- as_tibble(just_silent)
View(just_silent)

normalized_all <- as_tibble(rbind(normalized,just_silent))
View(normalized_all)

all_phrase <- normalized_all %>% 
  group_by(phrase,vocalization) %>% 
  ggplot(aes(x=new_time, y=voltage_microv, color=factor(vocalization))) +
  geom_line(stat="identity") +
  facet_wrap(~ phrase) +
  labs(x="Time (sec)", y="Voltage (uV)", title="Peak heights by normalized start time", color="Vocalization")
png(filename = "all_phrases.png")
all_phrase
dev.off()

best_phrase <- normalized_all %>% 
  filter(phrase==2 | phrase==4 | phrase==5) %>%
  group_by(phrase,vocalization) %>% 
  ggplot(aes(x=new_time, y=voltage_microv, color=factor(vocalization))) +
  geom_line(stat="identity") +
  facet_wrap(~ phrase, ncol=2) +
  labs(x="Time (sec)", y="Voltage (uV)", title="Peak heights by normalized start time", color="Vocalization")
png(filename = "best_phrases.png")
best_phrase
dev.off()

all_phrase_together <- normalized_all %>% 
  group_by(phrase,vocalization) %>% 
  ggplot(aes(x=new_time, y=factor(phrase), color=factor(vocalization))) +
  geom_point() +
  labs(x="Time (sec)", y="Phrase", title="Peak heights by normalized start time", color="Vocalization")
png(filename = "all_phrases.png")
all_phrase_together
dev.off()

# Phrase 1 only data

peak_phrase1 <- as_tibble(read.csv2("/media/maddy/Seagate Portable Drive/git/Bio_381/group_IP/reformat2_phrase1.csv", header=TRUE, sep=","))
View(peak_phrase1)
peak_phrase1$subject <- as.numeric(as.character(peak_phrase1$subject))
peak_phrase1$vocalization <- as.character(peak_phrase1$vocalization)
peak_phrase1$time <- as.double(as.character(peak_phrase1$time))
peak_phrase1$voltage <- as.double(as.character(peak_phrase1$voltage))

alt_norm_p_spoken <- peak_phrase1 %>% 
  filter(vocalization == "spoken") %>%
  group_by(subject) %>%
  summarize(start_time = min(time))
alt_normalized_p_spoken <- peak_phrase1 %>%
  filter(vocalization == "spoken") %>%
  group_by(subject) %>%
  mutate(norm_time = time - alt_norm_p_spoken$start_time[subject])
alt_normalized_p_spoken <- as_tibble(alt_normalized_p_spoken)

alt_norm_p_silent <- peak_phrase1 %>% 
  filter(vocalization == "silent") %>%
  group_by(subject) %>%
  summarize(start_time = min(time))
alt_normalized_p_silent <- peak_phrase1 %>%
  filter(vocalization == "silent") %>%
  group_by(subject) %>%
  mutate(norm_time = time - alt_norm_p_silent$start_time[subject])
alt_normalized_p_silent <- as_tibble(alt_normalized_p_silent)

alt_normalized_all <- as_tibble(rbind(alt_normalized_p_spoken, alt_normalized_p_silent))

norm_factor_p <- peak_phrase1 %>% 
  group_by(subject,vocalization) %>%
  summarize(start_time = min(time)) %>%
  mutate(time_diff = start_time - lag(start_time)) %>%
  filter(vocalization == "spoken")

normalized_p <- peak_phrase1 %>%
  filter(vocalization == "spoken") %>%
  group_by(subject) %>%
  mutate(new_time = time - norm_factor_p$time_diff[subject])
normalized_p <- as_tibble(normalized_p)

just_silent_p <- peak_phrase1 %>% filter(vocalization == "silent") %>% mutate(new_time = time)
just_silent_p <- as_tibble(just_silent_p)

normalized_all_p <- as_tibble(rbind(normalized_p,just_silent_p))
View(normalized_all_p)

phrase_1 <- normalized_all_p %>%
  group_by(subject,vocalization) %>%
  ggplot(aes(x=new_time, y=voltage, color=factor(vocalization))) +
  geom_point() +
  facet_wrap(~ subject, ncol=2)
  labs(x="Time (sec)", y="Subject", title="Peak heights by normalized start time", color="Vocalization")
phrase_1

phrase_1_alt <- alt_normalized_all %>%
  group_by(subject,vocalization) %>%
  ggplot(aes(x=norm_time, y=factor(subject), color=factor(vocalization))) +
  geom_point() +
  labs(x="Time (sec)", y="Subject", title="Peak heights by normalized start time", color="Vocalization")
png(filename = "phrase_1_allsubj.png")
phrase_1_alt
dev.off()

phrase_1_alt_line <- alt_normalized_all %>%
  group_by(subject,vocalization) %>%
  ggplot(aes(x=norm_time, y=voltage, color=factor(vocalization))) +
  geom_line(stat="identity") +
  facet_wrap(~ subject, ncol=2) +
  labs(x="Time (sec)", y="Subject", title="Peak heights by normalized start time", color="Vocalization")
png(filename = "phrase_1_lines.png")
phrase_1_alt_line
dev.off()
```